"""Autogenerated dummy service module enabling code completion in Python editors
 MODO Build #654077
"""

from . import object

class AudioAnim(object):
    def Audio(self):
        """Audio object = Audio()"""
        ...

    def End(self):
        """float = End()"""
        ...

    def Item(self):
        """Item object = Item()"""
        ...

    def ItemAudio(self, obj):
        """Unknown object = ItemAudio(object obj)"""
        ...

    def ItemSample(self, obj, loop, time, type, value):
        """ItemSample(object obj,integer loop,float time,integer type,pointer value)"""
        ...

    def Loop(self):
        """integer = Loop()"""
        ...

    def Mute(self):
        """integer = Mute()"""
        ...

    def Playing(self):
        """integer = Playing()"""
        ...

    def Preview(self, startTime, endTime):
        """Audio object = Preview(float startTime,float endTime)"""
        ...

    def Sample(self, time, type, value):
        """Sample(float time,integer type,data[] value)"""
        ...

    def Scrub(self):
        """integer = Scrub()"""
        ...

    def Start(self):
        """float = Start()"""
        ...



class Cache(object):
    def GetData(self, name, key):
        """Unknown object = GetData(string name,integer key)"""
        ...

    def PurgeData(self, name):
        """PurgeData(string name)"""
        ...

    def Register(self, name):
        """Register(string name)"""
        ...

    def Release(self, name):
        """Release(string name)"""
        ...

    def ScriptQuery(self):
        """Unknown object = ScriptQuery()"""
        ...

    def SetData(self, name, key, data):
        """SetData(string name,integer key,object data)"""
        ...



class ChannelUI(object):
    def ChannelDescription(self, item, channel):
        """string desc = ChannelDescription(object item,integer channel)"""
        ...

    def ChannelToolTip(self, item, channel):
        """string tip = ChannelToolTip(object item,integer channel)"""
        ...

    def ChannelUserName(self, item, channel):
        """string = ChannelUserName(object item,integer channel)"""
        ...

    def ItemTypeDesc(self, typeID, useSuper):
        """string name = ItemTypeDesc(integer typeID,integer useSuper)"""
        ...

    def ItemTypeIconText(self, typeID, useSuper):
        """string = ItemTypeIconText(integer typeID,integer useSuper)"""
        ...

    def ItemTypeName(self, typeID, useSuper):
        """string name = ItemTypeName(integer typeID,integer useSuper)"""
        ...

    def MeshMapUserName(self, name, addIcon):
        """string = MeshMapUserName(string name,integer addIcon)"""
        ...

    def ScriptQuery(self):
        """Unknown object = ScriptQuery()"""
        ...



class ColorMapping(object):
    def ConfigCount(self):
        """integer = ConfigCount()"""
        ...

    def ConfigFullPath(self, index):
        """string configPath = ConfigFullPath(integer index)"""
        ...

    def ConfigName(self, index):
        """string configName = ConfigName(integer index)"""
        ...

    def GetDisplayColorMapping(self):
        """ColorMapping object = GetDisplayColorMapping()"""
        ...

    def GetNumericColorMapping(self):
        """ColorMapping object = GetNumericColorMapping()"""
        ...

    def MakeColorMapping(self, colorspaceName, toLinear):
        """ColorMapping object = MakeColorMapping(string colorspaceName,integer toLinear)"""
        ...

    def RegisterColorspaceForConfig(self, configName, colorspaceName):
        """RegisterColorspaceForConfig(string configName,string colorspaceName)"""
        ...



class Command(object):
    def AliasCreate(self, name, targetCmd, targetTag, targetName, args):
        """AliasCreate(string name,object targetCmd,integer targetTag,string targetName,string args)"""
        ...

    def AliasDelete(self, alias, tag, name):
        """AliasDelete(object alias,integer tag,string name)"""
        ...

    def AllocateUIHintsFromCommand(self, cmd, argIndex):
        """UIHints object = AllocateUIHintsFromCommand(object cmd,integer argIndex)"""
        ...

    def ArgsAsString(self, cmd, includeCmd):
        """string = ArgsAsString(object cmd,integer includeCmd)"""
        ...

    def ArgsAsStringLen(self, cmd, includeCmd):
        """string = ArgsAsStringLen(object cmd,integer includeCmd)"""
        ...

    def ArgsAsStringWithOptions(self, cmd, options):
        """string = ArgsAsStringWithOptions(object cmd,integer options)"""
        ...

    def BlockBegin(self, name, flags):
        """BlockBegin(string name,integer flags)"""
        ...

    def BlockEnd(self):
        """BlockEnd()"""
        ...

    def CancelDoAtEndOfRootLevelUndoableCommand(self, visitor):
        """CancelDoAtEndOfRootLevelUndoableCommand(object visitor)"""
        ...

    def CommandByIndex(self, index):
        """Command object = CommandByIndex(integer index)"""
        ...

    def CommandCount(self):
        """integer count = CommandCount()"""
        ...

    def CreateQueryObject(self, typeName):
        """ValueArray object = CreateQueryObject(string typeName)"""
        ...

    def CurrentExecDepth(self):
        """integer depth = CurrentExecDepth()"""
        ...

    def CurrentExecIsRoot(self, ignoreBlocks):
        """CurrentExecIsRoot(integer ignoreBlocks)"""
        ...

    def DoAtEndOfRootLevelUndoableCommand(self, visitor):
        """DoAtEndOfRootLevelUndoableCommand(object visitor)"""
        ...

    def ExecEntryAsArgString(self, index):
        """string = ExecEntryAsArgString(integer index)"""
        ...

    def ExecEntryName(self, index):
        """string name = ExecEntryName(integer index)"""
        ...

    def ExecEntryType(self, index):
        """integer type = ExecEntryType(integer index)"""
        ...

    def ExecEntryUserName(self, index):
        """string userName = ExecEntryUserName(integer index)"""
        ...

    def ExecFlagsAsPrefixString(self, flags):
        """string = ExecFlagsAsPrefixString(integer flags)"""
        ...

    def ExecuteArgString(self, execFlags, tag, args):
        """ExecuteArgString(integer execFlags,integer tag,string args)"""
        ...

    def ExecuteArgString2(self, execFlags, tag, args):
        """Command object = ExecuteArgString2(integer execFlags,integer tag,string args)"""
        ...

    def ExecuteAttribObject(self, execFlags, tag, cmdName, attribArgs):
        """ExecuteAttribObject(integer execFlags,integer tag,string cmdName,object attribArgs)"""
        ...

    def ExecuteAttribObject2(self, execFlags, tag, cmdName, attribArgs):
        """Command object = ExecuteAttribObject2(integer execFlags,integer tag,string cmdName,object attribArgs)"""
        ...

    def ExecuteBooleanArgString(self, execFlags, tag, args):
        """ExecuteBooleanArgString(integer execFlags,integer tag,string args)"""
        ...

    def ExecuteBooleanArgString2(self, execFlags, tag, args):
        """Command object = ExecuteBooleanArgString2(integer execFlags,integer tag,string args)"""
        ...

    def ExecuteImplicitScript(self, definition, execFlags):
        """ExecuteImplicitScript(string definition,integer execFlags)"""
        ...

    def ExecuteImplicitScript2(self, definition, execFlags):
        """Command object = ExecuteImplicitScript2(string definition,integer execFlags)"""
        ...

    def ExecuteSpecial(self, execFlags, cmd, specialArgIndex):
        """ExecuteSpecial(integer execFlags,object cmd,integer specialArgIndex)"""
        ...

    def ExecuteToggleArgString(self, execFlags, tag, args, newState):
        """ExecuteToggleArgString(integer execFlags,integer tag,string args,integer newState)"""
        ...

    def ExecuteToggleArgString2(self, execFlags, tag, args, newState):
        """Command object = ExecuteToggleArgString2(integer execFlags,integer tag,string args,integer newState)"""
        ...

    def GetNameSep(self):
        """integer sep = GetNameSep()"""
        ...

    def GetToggleArgState(self, cmd):
        """(integer state,Value object) = GetToggleArgState(object cmd)"""
        ...

    def IsAliased(self, cmd):
        """boolean = IsAliased(object cmd)"""
        ...

    def IsBooleanArgString(self, string):
        """boolean = IsBooleanArgString(string string)"""
        ...

    def IsContainer(self, cmd):
        """boolean = IsContainer(object cmd)"""
        ...

    def IsGlobalInteractionOK(self):
        """boolean = IsGlobalInteractionOK()"""
        ...

    def IsImplicitScript(self, definition):
        """boolean = IsImplicitScript(string definition)"""
        ...

    def IsToggleArgString(self, string):
        """boolean = IsToggleArgString(string string)"""
        ...

    def Lookup(self, name):
        """integer tag = Lookup(string name)"""
        ...

    def MasterStatus(self):
        """integer status = MasterStatus()"""
        ...

    def ParseArgString(self, cmd, alertFlags, args):
        """ParseArgString(object cmd,integer alertFlags,string args)"""
        ...

    def ParseAttribObject(self, cmd, alertFlags, attribArgs):
        """ParseAttribObject(object cmd,integer alertFlags,object attribArgs)"""
        ...

    def PostModeBegin(self, cmd, tag, name, args, postEndObj):
        """PostModeBegin(object cmd,integer tag,string name,string args,object postEndObj)"""
        ...

    def PostModeEnd(self):
        """PostModeEnd()"""
        ...

    def PostModeRestart(self):
        """PostModeRestart()"""
        ...

    def PostModeState(self):
        """PostModeState()"""
        ...

    def ProcessStringFlags(self, flags, string):
        """(integer newFlags,string afterFlags) = ProcessStringFlags(integer flags,string string)"""
        ...

    def Proto(self, tag, name):
        """Command object = Proto(integer tag,string name)"""
        ...

    def ProtoFromCommand(self, cmd):
        """Command object = ProtoFromCommand(object cmd)"""
        ...

    def Query(self, cmd, index):
        """ValueArray object = Query(object cmd,integer index)"""
        ...

    def QueryArgString(self, cmd, alertFlags, args, includesCmdName):
        """(ValueArray object,integer queryIndex) = QueryArgString(object cmd,integer alertFlags,string args,integer includesCmdName)"""
        ...

    def RefireBegin(self):
        """RefireBegin()"""
        ...

    def RefireBlock(self):
        """string name = RefireBlock()"""
        ...

    def RefireCmd(self):
        """Command object = RefireCmd()"""
        ...

    def RefireEnd(self):
        """RefireEnd()"""
        ...

    def RefireState(self):
        """integer state = RefireState()"""
        ...

    def SandboxAddObject(self, object):
        """SandboxAddObject(object object)"""
        ...

    def SandboxBegin(self, flags):
        """SandboxBegin(integer flags)"""
        ...

    def SandboxEnd(self):
        """SandboxEnd()"""
        ...

    def SandboxFlags(self):
        """integer flags = SandboxFlags()"""
        ...

    def SandboxObjectByCommand(self, cmd):
        """Unknown object = SandboxObjectByCommand(object cmd)"""
        ...

    def SandboxObjectByIndex(self, index):
        """Unknown object = SandboxObjectByIndex(integer index)"""
        ...

    def SandboxObjectCount(self):
        """integer count = SandboxObjectCount()"""
        ...

    def SandboxObjectLookup(self, guid):
        """Unknown object = SandboxObjectLookup(string guid)"""
        ...

    def SandboxState(self):
        """SandboxState()"""
        ...

    def ScriptQuery(self):
        """Unknown object = ScriptQuery()"""
        ...

    def SetIsGlobalInteractionOK(self, isOK):
        """SetIsGlobalInteractionOK(integer isOK)"""
        ...

    def SetNameSep(self, sep):
        """SetNameSep(integer sep)"""
        ...

    def SetToggleArgState(self, cmd, state):
        """SetToggleArgState(object cmd,integer state)"""
        ...

    def Spawn(self, tag, name):
        """Command object = Spawn(integer tag,string name)"""
        ...

    def SpawnFromCommand(self, cmd):
        """Command object = SpawnFromCommand(object cmd)"""
        ...

    def SpawnFromString(self, args):
        """(integer execFlags,integer queryArgIndex,Command object) = SpawnFromString(string args)"""
        ...

    def SpawnImplicitScript(self, definition):
        """Command object = SpawnImplicitScript(string definition)"""
        ...

    def SpawnUnaliased(self, tag, name):
        """Command object = SpawnUnaliased(integer tag,string name)"""
        ...

    def Usage(self, cmd):
        """string buffer = Usage(object cmd)"""
        ...



class Deformer(object):
    def DeformEltToItem(self, elt):
        """object = DeformEltToItem(id elt)"""
        ...

    def DeformerChannel(self, item):
        """integer index = DeformerChannel(object item)"""
        ...

    def DeformerDeformationItem(self, defItem):
        """item object = DeformerDeformationItem(object defItem)"""
        ...

    def DeformerFlags(self, item):
        """integer flags = DeformerFlags(object item)"""
        ...

    def GroupDeformer(self, dgroup, chanRead):
        """GroupDeformer object = GroupDeformer(object dgroup,object chanRead)"""
        ...

    def InvalidateTargets(self, scene):
        """InvalidateTargets(object scene)"""
        ...

    def ItemToDeformElt(self, item):
        """id = ItemToDeformElt(object item)"""
        ...

    def MergeChangeState(self, c1, c2):
        """MergeChangeState(integer c1,integer c2)"""
        ...

    def MeshByIndex(self, defItem, index):
        """Item object = MeshByIndex(object defItem,integer index)"""
        ...

    def MeshCount(self, defItem):
        """integer count = MeshCount(object defItem)"""
        ...

    def ScriptQuery(self):
        """Unknown object = ScriptQuery()"""
        ...

    def StackTargetByIndex(self, defItem, index):
        """Item object = StackTargetByIndex(object defItem,integer index)"""
        ...

    def StackTargetCount(self, defItem):
        """integer count = StackTargetCount(object defItem)"""
        ...



class DirCache(object):
    def AddClient(self):
        """AddClient()"""
        ...

    def ArePathsEqual(self, path1, path2):
        """ArePathsEqual(string path1,string path2)"""
        ...

    def AttributesChanged(self, dirCacheEntry, which, attribute):
        """AttributesChanged(object dirCacheEntry,integer which,string attribute)"""
        ...

    def CachedThumbnailAsyncCancel(self, ident):
        """CachedThumbnailAsyncCancel(string ident)"""
        ...

    def CanBeRenamed(self, path):
        """CanBeRenamed(string path)"""
        ...

    def IsChildOfPath(self, possibleChild, parentToTestAgainsts, orIsSame):
        """IsChildOfPath(string possibleChild,string parentToTestAgainsts,integer orIsSame)"""
        ...

    def Lookup(self, path):
        """DirCacheEntry object = Lookup(string path)"""
        ...

    def MakeDirHierarchy(self, path, skipLastPart):
        """MakeDirHierarchy(string path,integer skipLastPart)"""
        ...

    def MakeUniqueIn(self, object, filename):
        """string = MakeUniqueIn(object object,string filename)"""
        ...

    def ParseName(self, filename, baseName, baseNameLen, path, pathLen):
        """ParseName(string filename,byte[] baseName,integer baseNameLen,byte[] path,integer pathLen)"""
        ...

    def PathCompose(self, filename, filenameLen, baseName, path):
        """PathCompose(byte[] filename,integer filenameLen,string baseName,string path)"""
        ...

    def RemoveClient(self):
        """RemoveClient()"""
        ...

    def RootByIndex(self, index):
        """DirCacheEntry object = RootByIndex(integer index)"""
        ...

    def RootCount(self):
        """integer count = RootCount()"""
        ...

    def RootLock(self):
        """RootLock()"""
        ...

    def RootUnlock(self):
        """RootUnlock()"""
        ...

    def ScanForChanges(self, path):
        """ScanForChanges(string path)"""
        ...

    def ScriptQuery(self):
        """Unknown object = ScriptQuery()"""
        ...

    def SetPosOnDrop(self, path, dest):
        """SetPosOnDrop(string path,object dest)"""
        ...

    def ToLocalAlias(self, path):
        """string = ToLocalAlias(byte[] path)"""
        ...



class Drop(object):
    def Action(self):
        """(string serverName,integer actionCode) = Action()"""
        ...

    def Destination(self):
        """Unknown object = Destination()"""
        ...

    def ScriptQuery(self):
        """Unknown object = ScriptQuery()"""
        ...

    def Source(self):
        """(string sourceType,Unknown object) = Source()"""
        ...



class File(object):
    def AllocRedirect(self):
        """FileRedirect object = AllocRedirect()"""
        ...

    def AllocReference(self, path):
        """FileReference object = AllocReference(string path)"""
        ...

    def ArePathsEqual(self, path1, path2):
        """boolean = ArePathsEqual(string path1,string path2)"""
        ...

    def ComposePath(self, basename, path):
        """string = ComposePath(string basename,string path)"""
        ...

    def DirDelete(self, filename):
        """DirDelete(string filename)"""
        ...

    def Execute(self, show, force32):
        """string argv = Execute(integer show,integer force32)"""
        ...

    def FileCopy(self, srcFilePath, dstFilePath, overwrite):
        """FileCopy(string srcFilePath,string dstFilePath,integer overwrite)"""
        ...

    def FileDateString(self, filename):
        """string = FileDateString(string filename)"""
        ...

    def FileDelete(self, filename):
        """FileDelete(string filename)"""
        ...

    def FileFromURL(self, url):
        """string = FileFromURL(string url)"""
        ...

    def FileSystemPath(self, name):
        """string path = FileSystemPath(string name)"""
        ...

    def FileToURL(self, filename):
        """string = FileToURL(string filename)"""
        ...

    def FindSequenceBounds(self, pattern):
        """(integer first,integer last) = FindSequenceBounds(string pattern)"""
        ...

    def FindSequencePattern(self, filename):
        """string = FindSequencePattern(string filename)"""
        ...

    def FromLocal(self, local):
        """string = FromLocal(string local)"""
        ...

    def GenerateSequenceName(self, pattern, frame):
        """string = GenerateSequenceName(string pattern,integer frame)"""
        ...

    def IsAbsolutePath(self, path):
        """boolean = IsAbsolutePath(string path)"""
        ...

    def MakeDirectory(self, path):
        """MakeDirectory(string path)"""
        ...

    def MakeLegalFilename(self, filename, replaceDot):
        """MakeLegalFilename(byte[] filename,integer replaceDot)"""
        ...

    def MakeRelative(self, filename, path):
        """string = MakeRelative(string filename,string path)"""
        ...

    def MakeUnique(self, filename):
        """string = MakeUnique(string filename)"""
        ...

    def OpenFileWithDefaultApp(self, filename):
        """OpenFileWithDefaultApp(string filename)"""
        ...

    def ParsePath(self, filename, component):
        """string = ParsePath(string filename,integer component)"""
        ...

    def PkgCountFiles(self, package):
        """integer = PkgCountFiles(string package)"""
        ...

    def PkgExtract(self, package, file, dest):
        """PkgExtract(string package,string file,string dest)"""
        ...

    def PkgExtractAll(self, package, dest, subDir):
        """PkgExtractAll(string package,string dest,string subDir)"""
        ...

    def PkgFilename(self, package, id):
        """string = PkgFilename(string package,integer id)"""
        ...

    def PkgHasFile(self, package, file):
        """PkgHasFile(string package,string file)"""
        ...

    def RenameFile(self, from_str, to_str):
        """RenameFile(string from_str,string to_str)"""
        ...

    def RevealInFileViewer(self, filename):
        """RevealInFileViewer(string filename)"""
        ...

    def SetExtension(self, filename, extension):
        """string = SetExtension(string filename,string extension)"""
        ...

    def TestFileMode(self, filename):
        """integer mode = TestFileMode(string filename)"""
        ...

    def TestFileType(self, filename):
        """(boolean,integer type) = TestFileType(string filename)"""
        ...

    def ToLocal(self, neutral):
        """string = ToLocal(byte[] neutral)"""
        ...

    def ToLocalAlias(self, neutral):
        """string = ToLocalAlias(string neutral)"""
        ...

    def ValidateLicense(self, product, versionNum):
        """ValidateLicense(string product,integer versionNum)"""
        ...



class GUID(object):
    def Class(self, guid):
        """string = Class(string guid)"""
        ...

    def ClassName(self, guid):
        """string = ClassName(string guid)"""
        ...

    def Compare(self, guid1, guid2):
        """integer = Compare(string guid1,string guid2)"""
        ...

    def Fixed(self, guid):
        """string = Fixed(string guid)"""
        ...

    def GetName(self, guid):
        """string = GetName(string guid)"""
        ...

    def Translate(self, guidStr):
        """string = Translate(string guidStr)"""
        ...



class Host(object):
    def AddServer(self, factory):
        """AddServer(object factory)"""
        ...

    def DefaultPath(self):
        """string path = DefaultPath()"""
        ...

    def LookupServer(self, className, name, allowLoad):
        """Factory object = LookupServer(string className,string name,integer allowLoad)"""
        ...

    def NumServers(self, className):
        """integer = NumServers(string className)"""
        ...

    def SaverSave(self, filename, format, object, monitor):
        """SaverSave(string filename,string format,object object,object monitor)"""
        ...

    def SaverVerify(self, format, object, msg):
        """SaverVerify(string format,object object,object msg)"""
        ...

    def ScriptQuery(self):
        """Unknown object = ScriptQuery()"""
        ...

    def ServerByIndex(self, className, index):
        """Factory object = ServerByIndex(string className,integer index)"""
        ...

    def ServerGetIndex(self, className, name):
        """integer index = ServerGetIndex(string className,string name)"""
        ...

    def SpawnForTagsOnly(self):
        """SpawnForTagsOnly()"""
        ...

    def TestServer(self, className, name):
        """boolean = TestServer(string className,string name)"""
        ...

    def UpdateModule(self, name):
        """UpdateModule(string name)"""
        ...



class IO(object):
    def OpenBlockStore(self, filename, format, flags):
        """(boolean,BlockStore object) = OpenBlockStore(string filename,string format,integer flags)"""
        ...

    def PeekOptions(self):
        """object = PeekOptions()"""
        ...

    def ScriptQuery(self):
        """Unknown object = ScriptQuery()"""
        ...

    def SetOptions(self, options):
        """SetOptions(object options)"""
        ...



class Image(object):
    def Composite(self, dest, source, pos):
        """Composite(object dest,object source,vector pos)"""
        ...

    def Create(self, width, height, type, maxIndex):
        """Image object = Create(integer width,integer height,integer type,integer maxIndex)"""
        ...

    def CreateCrop(self, sourceImage, x, y, w, h):
        """Image object = CreateCrop(object sourceImage,float x,float y,float w,float h)"""
        ...

    def CreateLayered(self, width, height, layerNum):
        """Unknown object = CreateLayered(integer width,integer height,integer layerNum)"""
        ...

    def DrawLine(self, image, p0, p1, color):
        """DrawLine(object image,vector p0,vector p1,vector color)"""
        ...

    def Duplicate(self, source, type):
        """Image object = Duplicate(object source,integer type)"""
        ...

    def ImageGetBuffer(self, sourceImage, type, buf):
        """ImageGetBuffer(object sourceImage,integer type,data[] buf)"""
        ...

    def Kelvin2RGB(self, kelvin):
        """vector rgbColor = Kelvin2RGB(float kelvin)"""
        ...

    def Load(self, filePath):
        """Image object = Load(string filePath)"""
        ...

    def LoadNoCache(self, filePath):
        """Image object = LoadNoCache(string filePath)"""
        ...

    def RGB2Kelvin(self, rgbColor):
        """float kelvin = RGB2Kelvin(vector rgbColor)"""
        ...

    def Resample(self, dest, source, hint):
        """Resample(object dest,object source,integer hint)"""
        ...

    def Save(self, image, filePath, format, monitor):
        """Save(object image,string filePath,string format,object monitor)"""
        ...

    def SaveLayered(self, layeredImage, filePath, format, monitor):
        """SaveLayered(object layeredImage,string filePath,string format,object monitor)"""
        ...

    def ScriptQuery(self):
        """Unknown object = ScriptQuery()"""
        ...



class ImageMonitor(object):
    def RefreshViews(self, imageSource, immediate):
        """RefreshViews(string imageSource,integer immediate)"""
        ...

    def ScriptQuery(self):
        """Unknown object = ScriptQuery()"""
        ...

    def ServerByIndex(self, index):
        """ImageMonitor object = ServerByIndex(integer index)"""
        ...

    def ServerCount(self):
        """integer count = ServerCount()"""
        ...

    def ServerLookup(self, name):
        """ImageMonitor object = ServerLookup(string name)"""
        ...

    def ServerNameByIndex(self, index):
        """string name = ServerNameByIndex(integer index)"""
        ...

    def ServerUserNameByIndex(self, index):
        """string name = ServerUserNameByIndex(integer index)"""
        ...

    def SetImage(self, imageSource, image, frameBuffer, bufferIndex, x1, y1, x2, y2, imageProc, processedThumbnail):
        """SetImage(string imageSource,object image,object frameBuffer,integer bufferIndex,float x1,float y1,float x2,float y2,object imageProc,object processedThumbnail)"""
        ...

    def SourceCount(self):
        """integer count = SourceCount()"""
        ...

    def SourceNameByIndex(self, index):
        """string name = SourceNameByIndex(integer index)"""
        ...

    def SourceUserNameByIndex(self, index):
        """string username = SourceUserNameByIndex(integer index)"""
        ...



class ImageProcessing(object):
    def Create(self):
        """ImageProcessing object = Create()"""
        ...

    def ScriptQuery(self):
        """Unknown object = ScriptQuery()"""
        ...



class InputMap(object):
    def CanEventsCoexist(self, im, event1, event2):
        """CanEventsCoexist(id im,integer event1,integer event2)"""
        ...

    def ContextCount(self):
        """integer count = ContextCount()"""
        ...

    def DefineClientTests(self, tester):
        """DefineClientTests(object tester)"""
        ...

    def DefineCustomEvent(self, event, name, flags):
        """DefineCustomEvent(integer event,string name,integer flags)"""
        ...

    def DefineGroup(self, group):
        """DefineGroup(string group)"""
        ...

    def DefineRegion(self, event, name):
        """DefineRegion(integer event,string name)"""
        ...

    def DefineStandardEvent(self, event, flags):
        """DefineStandardEvent(integer event,integer flags)"""
        ...

    def Desc(self, im):
        """string desc = Desc(id im)"""
        ...

    def EventCount(self, im):
        """integer count = EventCount(id im)"""
        ...

    def EventDesc(self, im, stateName, name, index):
        """string desc = EventDesc(id im,string stateName,string name,integer index)"""
        ...

    def EventFlags(self, im, index):
        """integer flags = EventFlags(id im,integer index)"""
        ...

    def EventHelpURL(self, im, stateName, name, index):
        """string helpURL = EventHelpURL(id im,string stateName,string name,integer index)"""
        ...

    def EventName(self, im, index):
        """string name = EventName(id im,integer index)"""
        ...

    def EventType(self, im, index):
        """integer type = EventType(id im,integer index)"""
        ...

    def EventUserName(self, im, stateName, name, index):
        """string username = EventUserName(id im,string stateName,string name,integer index)"""
        ...

    def FindEvent(self, im, name, type):
        """integer index = FindEvent(id im,string name,integer type)"""
        ...

    def FindRegion(self, im, name, type):
        """integer index = FindRegion(id im,string name,integer type)"""
        ...

    def GetMouseMap(self, im):
        """Unknown object = GetMouseMap(id im)"""
        ...

    def GroupUserName(self, path, depth):
        """string username = GroupUserName(string path,integer depth)"""
        ...

    def HelpURL(self, im):
        """string helpURL = HelpURL(id im)"""
        ...

    def Name(self, im):
        """string name = Name(id im)"""
        ...

    def RefreshContexts(self):
        """RefreshContexts()"""
        ...

    def RefreshStates(self, flags):
        """RefreshStates(integer flags)"""
        ...

    def RegionCount(self, im):
        """integer count = RegionCount(id im)"""
        ...

    def RegionDesc(self, im, stateName, name, index):
        """string desc = RegionDesc(id im,string stateName,string name,integer index)"""
        ...

    def RegionHelpURL(self, im, stateName, name, index):
        """string helpURL = RegionHelpURL(id im,string stateName,string name,integer index)"""
        ...

    def RegionName(self, im, i):
        """string name = RegionName(id im,integer i)"""
        ...

    def RegionType(self, im, i):
        """integer type = RegionType(id im,integer i)"""
        ...

    def RegionUserName(self, im, stateName, name, index):
        """string username = RegionUserName(id im,string stateName,string name,integer index)"""
        ...

    def ScriptQuery(self):
        """Unknown object = ScriptQuery()"""
        ...

    def StandardEventFlags(self, event):
        """integer flags = StandardEventFlags(integer event)"""
        ...

    def StandardEventName(self, event):
        """string name = StandardEventName(integer event)"""
        ...

    def StateCatUserName(self, cat):
        """string name = StateCatUserName(string cat)"""
        ...

    def StateCount(self, im):
        """integer count = StateCount(id im)"""
        ...

    def StateUIFallbacksCount(self, stateName):
        """integer count = StateUIFallbacksCount(string stateName)"""
        ...

    def StateUIFallbacksName(self, stateName, index):
        """string name = StateUIFallbacksName(string stateName,integer index)"""
        ...

    def StateUIListCatCount(self):
        """integer count = StateUIListCatCount()"""
        ...

    def StateUIListCatName(self, index):
        """string name = StateUIListCatName(integer index)"""
        ...

    def StateUIListCount(self, cat):
        """integer count = StateUIListCount(string cat)"""
        ...

    def StateUIListName(self, cat, index):
        """string name = StateUIListName(string cat,integer index)"""
        ...

    def StateUITestEvent(self, im, stateName, eventID):
        """StateUITestEvent(id im,string stateName,integer eventID)"""
        ...

    def StateUITestRegion(self, im, stateName, regionID):
        """StateUITestRegion(id im,string stateName,integer regionID)"""
        ...

    def StateUserName(self, state):
        """string name = StateUserName(string state)"""
        ...

    def TestState(self, im, state):
        """integer priority = TestState(id im,string state)"""
        ...

    def UpdateDeviceInstance(self, name):
        """UpdateDeviceInstance(string name)"""
        ...

    def UpdateDeviceList(self):
        """UpdateDeviceList()"""
        ...

    def UserName(self, im):
        """string username = UserName(id im)"""
        ...



class Interviewer(object):
    def Arm(self, serverName, target):
        """Arm(string serverName,integer target)"""
        ...

    def ClearDismissTimer(self, serverName):
        """ClearDismissTimer(string serverName)"""
        ...

    def Disarm(self, serverName, allowRearm):
        """Disarm(string serverName,integer allowRearm)"""
        ...

    def ScriptQuery(self):
        """Unknown object = ScriptQuery()"""
        ...

    def WasFired(self, serverName):
        """boolean = WasFired(string serverName)"""
        ...



class Layer(object):
    def Bounds(self, index: int) -> tuple[object.vector, object.vector]:
        """(vector min,vector max) = Bounds(integer index)"""
        ...

    def ClearMark(self, item: object.Unknown) -> None:
        """ClearMark(object item)"""
        ...

    def Count(self) -> int:
        """integer count = Count()"""
        ...

    def CurrentDeformer(self, meshItem):
        """string name = CurrentDeformer(object meshItem)"""
        ...

    def CurrentMap(self, type):
        """string name = CurrentMap(integer type)"""
        ...

    def CurveSmoothAngle(self, index):
        """float angle = CurveSmoothAngle(integer index)"""
        ...

    def Flags(self, index):
        """integer flags = Flags(integer index)"""
        ...

    def IsProcedural(self, index):
        """IsProcedural(integer index)"""
        ...

    def Item(self, index: int) -> object.Item:
        """Item object = Item(integer index)"""
        ...

    def ItemLookup(self, mode, item):
        """integer index = ItemLookup(integer mode,object item)"""
        ...

    def LayerChild(self, index, childNumber):
        """integer childIndex = LayerChild(integer index,integer childNumber)"""
        ...

    def LayerChildCount(self, index):
        """integer num = LayerChildCount(integer index)"""
        ...

    def LayerClip(self, index):
        """Item object = LayerClip(integer index)"""
        ...

    def LayerClipCount(self):
        """integer num = LayerClipCount()"""
        ...

    def LayerEdge(self, mode, index):
        """Unknown object = LayerEdge(integer mode,integer index)"""
        ...

    def LayerEdgeCount(self, mode: int) -> int:
        """integer num = LayerEdgeCount(integer mode)"""
        ...

    def LayerMaterial(self, index):
        """Item object = LayerMaterial(integer index)"""
        ...

    def LayerMaterialCount(self):
        """integer num = LayerMaterialCount()"""
        ...

    def LayerParent(self, index):
        """integer parentIndex = LayerParent(integer index)"""
        ...

    def LayerPart(self, index):
        """string part = LayerPart(integer index)"""
        ...

    def LayerPartCount(self):
        """integer num = LayerPartCount()"""
        ...

    def LayerPoly(self, mode, index):
        """Unknown object = LayerPoly(integer mode,integer index)"""
        ...

    def LayerPolyCount(self, mode: int) -> int:
        """integer num = LayerPolyCount(integer mode)"""
        ...

    def LayerSelSet(self, type: int, index: int) -> str:
        """string selSet = LayerSelSet(integer type,integer index)"""
        ...

    def LayerSelSetCount(self, type):
        """integer num = LayerSelSetCount(integer type)"""
        ...

    def LayerTagTexture(self, layer, type, tag, index):
        """Item object = LayerTagTexture(integer layer,integer type,string tag,integer index)"""
        ...

    def LayerTagTextureCount(self, layer, type, tag):
        """integer num = LayerTagTextureCount(integer layer,integer type,string tag)"""
        ...

    def LayerTexture(self, layer, index):
        """Item object = LayerTexture(integer layer,integer index)"""
        ...

    def LayerTextureCount(self, layer):
        """integer num = LayerTextureCount(integer layer)"""
        ...

    def LayerVMap(self, index):
        """Unknown object = LayerVMap(integer index)"""
        ...

    def LayerVMapCount(self):
        """integer num = LayerVMapCount()"""
        ...

    def LayerVertex(self, mode, index):
        """Unknown object = LayerVertex(integer mode,integer index)"""
        ...

    def LayerVertexCount(self, mode):
        """integer num = LayerVertexCount(integer mode)"""
        ...

    def Mesh(self, index):
        """Mesh object = Mesh(integer index)"""
        ...

    def Name(self, index):
        """string name = Name(integer index)"""
        ...

    def NameLookup(self, mode, name):
        """integer index = NameLookup(integer mode,string name)"""
        ...

    def PatchSubdivision(self, index):
        """integer level = PatchSubdivision(integer index)"""
        ...

    def Pivot(self, index):
        """float pivot = Pivot(integer index)"""
        ...

    def ScanAllocate(self, flags: int) -> object.LayerScan:
        """LayerScan object = ScanAllocate(integer flags)"""
        ...

    def ScanAllocateItem(self, item, flags):
        """LayerScan object = ScanAllocateItem(object item,integer flags)"""
        ...

    def Scene(self):
        """Scene object = Scene()"""
        ...

    def ScriptQuery(self):
        """Unknown object = ScriptQuery()"""
        ...

    def SetMark(self, item):
        """SetMark(object item)"""
        ...

    def SetScene(self, scene):
        """SetScene(object scene)"""
        ...

    def Slot(self, index):
        """integer slot = Slot(integer index)"""
        ...

    def SplinePatchSubdivision(self, index):
        """integer level = SplinePatchSubdivision(integer index)"""
        ...

    def TestMark(self, item):
        """integer = TestMark(object item)"""
        ...

    def XfrmAllocate(self, toolVec):
        """TransformScan object = XfrmAllocate(object toolVec)"""
        ...



class Listener(object):
    def AddListener(self, object):
        """AddListener(object object)"""
        ...

    def RemoveListener(self, object):
        """RemoveListener(object object)"""
        ...

    def ScriptQuery(self):
        """Unknown object = ScriptQuery()"""
        ...



class Log(object):
    def AcquireMonitor(self):
        """object = AcquireMonitor()"""
        ...

    def CreateEntryInfoBlock(self, type, blockName):
        """LogEntry object = CreateEntryInfoBlock(integer type,string blockName)"""
        ...

    def CreateEntryMessage(self, type, message):
        """LogEntry object = CreateEntryMessage(integer type,string message)"""
        ...

    def CreateEntryMessageFromMsgObj(self, msgObj):
        """LogEntry object = CreateEntryMessageFromMsgObj(object msgObj)"""
        ...

    def CreateEntryPaired(self, type):
        """LogEntry object = CreateEntryPaired(integer type)"""
        ...

    def DebugLogOutput(self, level, line):
        """DebugLogOutput(integer level,string line)"""
        ...

    def DebugLogOutputSys(self, level, logSystem, line):
        """DebugLogOutputSys(integer level,string logSystem,string line)"""
        ...

    def EnableLogging(self, systemName, state):
        """EnableLogging(string systemName,integer state)"""
        ...

    def ExceptionBlockCollect(self):
        """Message object = ExceptionBlockCollect()"""
        ...

    def ExceptionBlockStart(self):
        """ExceptionBlockStart()"""
        ...

    def ExceptionMessage(self, error, flags):
        """object = ExceptionMessage(integer error,integer flags)"""
        ...

    def InfoBlockByIndex(self, index):
        """LogInfoBlock object = InfoBlockByIndex(integer index)"""
        ...

    def InfoBlockCount(self):
        """integer count = InfoBlockCount()"""
        ...

    def InfoBlockFieldGetParts(self, name):
        """(string group,string sub) = InfoBlockFieldGetParts(string name)"""
        ...

    def InfoBlockFieldsAreSameGroup(self, name1, name2):
        """boolean = InfoBlockFieldsAreSameGroup(string name1,string name2)"""
        ...

    def InfoBlockLookup(self, name):
        """LogInfoBlock object = InfoBlockLookup(string name)"""
        ...

    def IsLoggingEnabled(self, systemName):
        """boolean = IsLoggingEnabled(string systemName)"""
        ...

    def MasterSubSystem(self):
        """Log object = MasterSubSystem()"""
        ...

    def ReplaceEntryMessage(self, logEntry, type, msg):
        """ReplaceEntryMessage(object logEntry,integer type,string msg)"""
        ...

    def ScriptQuery(self):
        """Unknown object = ScriptQuery()"""
        ...

    def SetMonitor(self, monitor):
        """SetMonitor(object monitor)"""
        ...

    def SubSystemByIndex(self, index):
        """Log object = SubSystemByIndex(integer index)"""
        ...

    def SubSystemCount(self):
        """integer count = SubSystemCount()"""
        ...

    def SubSystemLookup(self, name):
        """Log object = SubSystemLookup(string name)"""
        ...



class Mesh(object):
    def ConvertMesh(self, triGroupObj, meshObj):
        """ConvertMesh(object triGroupObj,object meshObj)"""
        ...

    def CreateMesh(self):
        """Mesh object = CreateMesh()"""
        ...

    def CreateSlice(self):
        """PolygonSlice object = CreateSlice()"""
        ...

    def CreateSolidDrill(self):
        """SolidDrill object = CreateSolidDrill()"""
        ...

    def CurveGroupFromMesh(self, mesh, xfrm):
        """Unknown object = CurveGroupFromMesh(object mesh,matrix xfrm)"""
        ...

    def IsMeshProcedural(self, item):
        """boolean = IsMeshProcedural(object item)"""
        ...

    def ItemFromMesh(self, mesh):
        """Item object = ItemFromMesh(object mesh)"""
        ...

    def MeshFromSurface(self, meshObj, surfItem, surfObj):
        """MeshFromSurface(object meshObj,object surfItem,object surfObj)"""
        ...

    def MeshFromTriGroup(self, meshObj, triGroupObj):
        """MeshFromTriGroup(object meshObj,object triGroupObj)"""
        ...

    def ModeCompose(self, set, clear):
        """integer mode = ModeCompose(string set,string clear)"""
        ...

    def ScriptQuery(self):
        """Unknown object = ScriptQuery()"""
        ...

    def SurfaceFromMesh(self, mesh, meshItem):
        """Surface object = SurfaceFromMesh(object mesh,object meshItem)"""
        ...

    def SurfaceToTriGroup(self, triGroupObj, surfObj):
        """SurfaceToTriGroup(object triGroupObj,object surfObj)"""
        ...

    def Tessellate(self, meshTess, meshSource, xfrm, flags):
        """Tessellate(object meshTess,object meshSource,matrix xfrm,integer flags)"""
        ...

    def TriGroupTransform(self, triGroupObj):
        """matrix xfrm = TriGroupTransform(object triGroupObj)"""
        ...

    def VMapDimension(self, type):
        """integer dimension = VMapDimension(integer type)"""
        ...

    def VMapIsContinuous(self, type):
        """boolean = VMapIsContinuous(integer type)"""
        ...

    def VMapIsEdgeMap(self, type):
        """boolean = VMapIsEdgeMap(integer type)"""
        ...

    def VMapLookupName(self, type):
        """string name = VMapLookupName(integer type)"""
        ...

    def VMapLookupType(self, name):
        """integer type = VMapLookupType(string name)"""
        ...

    def VMapZeroDefault(self, type):
        """boolean = VMapZeroDefault(integer type)"""
        ...

    def ValidateMetaData(self, mesh, name):
        """Unknown object = ValidateMetaData(object mesh,string name)"""
        ...



class Message(object):
    def Allocate(self):
        """Message object = Allocate()"""
        ...

    def ArgTypeDesc(self, argType):
        """string = ArgTypeDesc(string argType)"""
        ...

    def ArgTypeOptionDesc(self, argType, option):
        """string = ArgTypeOptionDesc(string argType,string option)"""
        ...

    def ArgTypeOptionUserName(self, argType, option):
        """string = ArgTypeOptionUserName(string argType,string option)"""
        ...

    def ArgTypeUserName(self, argType):
        """string = ArgTypeUserName(string argType)"""
        ...

    def Duplicate(self, msg):
        """Message object = Duplicate(object msg)"""
        ...

    def MessageText(self, msg):
        """string = MessageText(object msg)"""
        ...

    def MessageTextRich(self, msg):
        """string = MessageTextRich(object msg)"""
        ...

    def RawText(self, table, msg):
        """string text = RawText(string table,string msg)"""
        ...

    def RawTextRich(self, table, msg):
        """string text = RawTextRich(string table,string msg)"""
        ...

    def ScriptQuery(self):
        """Unknown object = ScriptQuery()"""
        ...

    def StringLookup(self, table, ident):
        """string text = StringLookup(string table,string ident)"""
        ...

    def StripRichText(self, string):
        """string stripped = StripRichText(string string)"""
        ...



class Network(object):
    def OneOffHostListAdd(self, hostname, ip, port):
        """OneOffHostListAdd(string hostname,integer ip,integer port)"""
        ...

    def OneOffHostListRemove(self, hostname, ip, port):
        """OneOffHostListRemove(string hostname,integer ip,integer port)"""
        ...

    def ScriptQuery(self):
        """Unknown object = ScriptQuery()"""
        ...



class Nodal(object):
    def AddSampleChan(self, eval, item, chanIndex, type):
        """(integer,integer idxArray) = AddSampleChan(object eval,object item,integer chanIndex,integer type)"""
        ...

    def AddSampleChanName(self, eval, item, chanName, type):
        """(integer,integer idxArray) = AddSampleChanName(object eval,object item,string chanName,integer type)"""
        ...

    def AnyDrivenChans(self, count):
        """(integer,integer chans) = AnyDrivenChans(integer count)"""
        ...

    def GetFloat(self, etor, index, orig):
        """(float,integer idxArray) = GetFloat(object etor,integer index,float orig)"""
        ...

    def GetInt(self, etor, index, orig):
        """(integer,integer idxArray) = GetInt(object etor,integer index,integer orig)"""
        ...

    def GetValue(self, etor, index, orig):
        """(pointer,integer idxArray) = GetValue(object etor,integer index,pointer orig)"""
        ...

    def IsDriven(self, item, chanIndex):
        """integer = IsDriven(object item,integer chanIndex)"""
        ...

    def IsDrivenName(self, item, chanName):
        """integer = IsDrivenName(object item,string chanName)"""
        ...



class NotifySys(object):
    def ByIndex(self, index):
        """Notifier object = ByIndex(integer index)"""
        ...

    def Count(self):
        """integer count = Count()"""
        ...

    def Lookup(self, name, args):
        """Notifier object = Lookup(string name,string args)"""
        ...

    def NameByIndex(self, index):
        """string name = NameByIndex(integer index)"""
        ...

    def ScriptQuery(self):
        """Unknown object = ScriptQuery()"""
        ...

    def Spawn(self, name, args):
        """Notifier object = Spawn(string name,string args)"""
        ...



class Packet(object):
    def AddPacket(self, vtype: object.VectorType, name: str, flags: int):
        """AddPacket(object vtype,string name,integer flags)"""
        ...

    def CreateVectorType(self, category: str) -> object.VectorType:
        """VectorType object = CreateVectorType(string category)"""
        ...

    def FastPacket(self, vector: object.VectorType, offset: int):
        """pointer = FastPacket(object vector,integer offset)"""
        ...

    def Lookup(self, category: str, name: str) -> int:
        """integer offset = Lookup(string category,string name)"""
        ...

    def Name(self, category: str, offset: int) -> str:
        """string name = Name(string category,integer offset)"""
        ...

    def ScriptQuery(self):
        """Unknown object = ScriptQuery()"""
        ...



class Particle(object):
    def EnumParticleFeatures(self, item, visitor):
        """EnumParticleFeatures(object item,object visitor)"""
        ...

    def EnumeratorEvaluate(self, attr, index):
        """ReplicatorEnumerator object = EnumeratorEvaluate(object attr,integer index)"""
        ...

    def EnumeratorPrepare(self, eval, replItem):
        """integer index = EnumeratorPrepare(object eval,object replItem)"""
        ...

    def FeatureIdent(self):
        """string ident = FeatureIdent()"""
        ...

    def FeatureOffset(self):
        """integer offset = FeatureOffset()"""
        ...

    def GetReplicatorEnumerator(self, replicatorItem):
        """ReplicatorEnumerator object = GetReplicatorEnumerator(object replicatorItem)"""
        ...

    def ItemToParticle(self, item, chanRead):
        """Unknown object = ItemToParticle(object item,object chanRead)"""
        ...

    def ScriptQuery(self):
        """Unknown object = ScriptQuery()"""
        ...

    def TriGroupBlend(self, triGroup0, triGroup1, blend):
        """TriGroupBlend(object triGroup0,object triGroup1,float blend)"""
        ...

    def TriGroupToParticle(self, triGroup):
        """Unknown object = TriGroupToParticle(object triGroup)"""
        ...



class Persistence(object):
    def AddValue(self, typeName):
        """AddValue(string typeName)"""
        ...

    def Configure(self, name, obj):
        """Configure(string name,object obj)"""
        ...

    def End(self):
        """PersistentEntry object = End()"""
        ...

    def ScriptQuery(self):
        """Unknown object = ScriptQuery()"""
        ...

    def Start(self, name, type):
        """Start(string name,integer type)"""
        ...



class Platform(object):
    def AppBuild(self) -> int:
        """ Get the build number of the application.

        integer build = AppBuild()"""
        ...

    def AppName(self) -> str:
        """ Get the application name.

        string name = AppName()"""
        ...

    def AppUsername(self) -> str:
        """string name = AppUsername()"""
        ...

    def AppVersion(self) -> int:
        """ Get the version number of the application.

        integer version = AppVersion()"""
        ...

    def AppVersionMajor(self) -> int:
        """integer version = AppVersionMajor()"""
        ...

    def AppVersionMinor(self) -> int:
        """integer version = AppVersionMinor()"""
        ...

    def AppVersionSP(self) -> int:
        """integer version = AppVersionSP()"""
        ...

    def CancelDoWhenUserIsIdle(self, visitor: object.Unknown, flags: int):
        """ This can be used to remove a pending user idle action.  It will do nothing if the
        idle action isn't armed.  Note that flags and the visitor pointer must be exactly
        the same as the one passed to DoWhenUserIsIdle(), or else it will not be found and
        the action will remain armed.

        .. Note::

            that when doing this from Python, you must pass the exact same visitor COM object
            (not Python object).  This is also necessary when removing listeners and canceling
            timers, as discussed here: https://learn.foundry.com/modo/developers/latest/sdk/pages/faqs/PythonFAQs.html#how-do-i-remove-a-listener-object-in-python

        CancelDoWhenUserIsIdle(object visitor,integer flags)"""
        ...

    def DoWhenUserIsIdle(self, visitor: object.Unknown, flags: int):
        """ This arms a user idle action, preferably only once until it has been fired, after
        which you can arm it again if necessary.

        DoWhenUserIsIdle(object visitor,integer flags)"""
        ...

    def ExpiresIn(self) -> int:
        """ Get the number of days left until the key expires, or -1 if the key is
        permanent.

        integer daysLeft = ExpiresIn()"""
        ...

    def ImportPathByIndex(self, index) -> str:
        """

        string path = ImportPathByIndex(integer index)"""
        ...

    def ImportPathCount(self) -> int:
        """ Walk the list of imported resource paths.

        integer index = ImportPathCount()"""
        ...

    def IsApp64Bit(self) -> bool:
        """ This returns true if the application (but not necessarily the platform) is 64 bit,
        and false if it's 32 bit.

        boolean = IsApp64Bit()"""
        ...

    def IsAppActive(self) -> bool:
        """boolean = IsAppActive()"""
        ...

    def IsHeadless(self) -> bool:
        """ This returns LXe_TRUE if the app is running in headless mode, and
        LXe_FALSE if not.

        boolean = IsHeadless()"""
        ...

    def IsSafeMode(self) -> bool:
        """boolean = IsSafeMode()"""
        ...

    def IsUserIdle(self) -> bool:
        """boolean = IsUserIdle()"""
        ...

    def LicensedTo(self) -> str:
        """ Get the user the app is licensed to.  If not licensed, this fails.

        string licensee = LicensedTo()"""
        ...

    def NumLicenses(self) -> int:
        """ Get the number of licenses this key works with.

        integer licenses = NumLicenses()"""
        ...

    def OSName(self) -> str:
        """string name = OSName()"""
        ...

    def OSType(self) -> int:
        """integer type = OSType()"""
        ...

    def OSVersion(self) -> str:
        """string version = OSVersion()"""
        ...

    def PathByIndex(self, index: int) -> str:
        """string path = PathByIndex(integer index)"""
        ...

    def PathCount(self) -> int:
        """ Walk the list of paths.

        integer count = PathCount()"""
        ...

    def PathNameByIndex(self, index) -> str:
        """ This returns the internal name of the path, or NULL if the path
        doesn't have one.

        string name = PathNameByIndex(integer index)"""
        ...

    def ScriptQuery(self) -> object.Unknown:
        """Unknown object = ScriptQuery()"""
        ...

    def SerialNumber(self) -> str:
        """ Get the serial number of this key.

        string serial = SerialNumber()"""
        ...

    def SessionStage(self) -> int:
        """ The current session stage can be read with this method, indicating the status of the
        application.

        The stage can be one of the following:

        #define LXfSESSIONSTAGE_STARTUP			    0x10000000
        #define LXfSESSIONSTAGE_READY			    0x20000000
        #define LXfSESSIONSTAGE_SHUTDOWN		    0x30000000

        #define LXiSESSIONSTAGE_NOT_READY		    0
        #define LXiSESSIONSTAGE_STARTUP_COMMANDS	(LXfSESSIONSTAGE_STARTUP  | 0)
        #define LXiSESSIONSTAGE_SYSTEM_READY		(LXfSESSIONSTAGE_READY    | 0)
        #define LXiSESSIONSTAGE_SHUTTING_DOWN		(LXfSESSIONSTAGE_SHUTDOWN | 0)

        integer stage = SessionStage()"""
        ...

    def TimerCancel(self, visitor: object.Unknown, idleFlags: int):
        """ A currently-running timer can be canceled with this function.  The visitor and flags
        must match what the timer was armed with.

        .. Note::

            that when doing this from Python, you must pass the exact same visitor COM object
            (not Python object).  This is also necessary when removing listeners and canceling
            user idle actions, as discussed here: https://learn.foundry.com/modo/developers/latest/sdk/pages/faqs/PythonFAQs.html#how-do-i-remove-a-listener-object-in-python

        TimerCancel(object visitor,integer idleFlags)"""
        ...

    def TimerStart(self, visitor: object.Unknown, milliseconds: int, idleFlags: int):
        """ Timers execute after a pre-determined number of milliseconds.  A timer executes only
        once, but you can re-arm it when it expires if you want.  The most common use of timers
        is to check files for changes or trigger periodic refreshes of part of the UI.

        .. Note::

            that timers can trigger at arbitrary and unsafe times, such as in the middle of
            rendering or while saving a file.  You should never execute a command from a timer,
            for example, but rather arm a user idle action (and even then executing commands is
            a bit iffy, since now you're adding something to the command history or undo list
            that the user didn't do directly, but sometimes it is necessary).

        If idleFlags are LXiUSERIDLE_ALWAYS, then the timer's visitor is called as soon as
        the timer expires.  Otherwise, the action is deferred until user idle state matches
        the flags.

        TimerStart(object visitor,integer milliseconds,integer idleFlags)"""
        ...



class PresetBrowser(object):
    def GetSpecialSelModePath(self, identifier):
        """string = GetSpecialSelModePath(string identifier)"""
        ...

    def IsViewportVisible(self, identifier, hash):
        """boolean = IsViewportVisible(string identifier,string hash)"""
        ...

    def RecognizeFile(self, path, flags):
        """(string serverName,string category) = RecognizeFile(string path,integer flags)"""
        ...

    def RecognizeFileForce(self, path, flags):
        """(string serverName,string category) = RecognizeFileForce(string path,integer flags)"""
        ...

    def Rescan(self, path):
        """Rescan(string path)"""
        ...

    def ScriptQuery(self):
        """Unknown object = ScriptQuery()"""
        ...

    def ServerByIndex(self, index):
        """PresetType object = ServerByIndex(integer index)"""
        ...

    def ServerCount(self):
        """integer count = ServerCount()"""
        ...

    def ServerLookup(self, name):
        """PresetType object = ServerLookup(string name)"""
        ...

    def ServerNameByIndex(self, index):
        """string name = ServerNameByIndex(integer index)"""
        ...

    def ServerUserNameByIndex(self, index):
        """string name = ServerUserNameByIndex(integer index)"""
        ...

    def SetSpecialSelModePath(self, identifier, path, asInteractive):
        """SetSpecialSelModePath(string identifier,string path,integer asInteractive)"""
        ...

    def SubtypeFromIdentifier(self, identifier):
        """integer subtype = SubtypeFromIdentifier(string identifier)"""
        ...

    def UpdateIdentifierState(self, identifier, path):
        """UpdateIdentifierState(string identifier,string path)"""
        ...



class PresetDestination(object):
    def ApplyMeshPresetToMeshPD(self, predest, filepath):
        """ApplyMeshPresetToMeshPD(object predest,string filepath)"""
        ...

    def ApplyProfilePDToMesh(self, predest, tolerance, freeze, axis, mesh):
        """ApplyProfilePDToMesh(object predest,float tolerance,integer freeze,integer axis,object mesh)"""
        ...

    def CreateMeshLayerPD(self, mesh, shadeItem):
        """Unknown object = CreateMeshLayerPD(object mesh,object shadeItem)"""
        ...

    def Profile1DPDFromPath(self, filepath):
        """Unknown object = Profile1DPDFromPath(string filepath)"""
        ...

    def Profile2DPDFromPath(self, filepath):
        """Unknown object = Profile2DPDFromPath(string filepath)"""
        ...

    def ShaderPDFromItem(self, item):
        """Unknown object = ShaderPDFromItem(object item)"""
        ...



class Preview(object):
    def CreatePreview(self):
        """Preview object = CreatePreview()"""
        ...

    def GetMeshPreview(self, item, width, height):
        """Unknown object = GetMeshPreview(object item,integer width,integer height)"""
        ...



class Render(object):
    def FrameDelete(self, slotIndex):
        """FrameDelete(integer slotIndex)"""
        ...

    def FrameRecall(self, slotIndex, ...Index, monitor):
        """FrameBuffer object = FrameRecall(integer slotIndex,integer ...Index,object monitor)"""
        ...

    def FrameRecallStats(self, slotIndex):
        """RenderStats object = FrameRecallStats(integer slotIndex)"""
        ...

    def FrameRecallThumbnail(self, slotIndex):
        """Image object = FrameRecallThumbnail(integer slotIndex)"""
        ...

    def FrameRenderPassCount(self, slotIndex):
        """integer numPasses = FrameRenderPassCount(integer slotIndex)"""
        ...

    def FrameRenderPassInfo(self, slotIndex, ...Index, name):
        """(integer width,integer height,integer outputCount,integer isStereo,integer eyeDisplay,integer stereoComposite) = FrameRenderPassInfo(integer slotIndex,integer ...Index,byte[] name)"""
        ...

    def FrameSaveImage(self, framebuffer, bufferIndex, filename, format, message, monitor):
        """FrameSaveImage(object framebuffer,integer bufferIndex,string filename,string format,object message,object monitor)"""
        ...

    def FrameSaveLayered(self, framebuffer, filename, format, message, monitor):
        """FrameSaveLayered(object framebuffer,string filename,string format,object message,object monitor)"""
        ...

    def FrameSavePassLayered(self, framebuffer, filename, format, message, monitor):
        """FrameSavePassLayered(object framebuffer,string filename,string format,object message,object monitor)"""
        ...

    def FrameSavePassesAsImages(self, slotIndex, filename, format, message, monitor):
        """FrameSavePassesAsImages(integer slotIndex,string filename,string format,object message,object monitor)"""
        ...

    def FrameSavePassesAsLayeredImages(self, slotIndex, filename, format, message, monitor):
        """FrameSavePassesAsLayeredImages(integer slotIndex,string filename,string format,object message,object monitor)"""
        ...

    def FrameStore(self, frameBuffer, writePixels):
        """FrameStore(object frameBuffer,integer writePixels)"""
        ...

    def FrameStoreStats(self, slotIndex, stats):
        """FrameStoreStats(integer slotIndex,object stats)"""
        ...

    def FrameStoreThumbnail(self, slotIndex, image):
        """FrameStoreThumbnail(integer slotIndex,object image)"""
        ...

    def FrameTestRecall(self, slotIndex, ...Index):
        """boolean = FrameTestRecall(integer slotIndex,integer ...Index)"""
        ...

    def JobAbort(self):
        """ This aborts a currently running render job.  It will fail if no jobs are
        currently rendering.  Note that although this function returns immediately,
        it may take some time before the render has finished aborting.

        JobAbort()

        """
        ...

    def JobCleanup(self, clearJob):
        """JobCleanup(integer clearJob)"""
        ...

    def JobCurrent(self):
        """ This returns the current render job, failing if there is no current job.  The
        returned object must be released by the caller if the method returns success.

        RenderJob object = JobCurrent()"""
        ...

    def JobIsSlave(self):
        """integer = JobIsSlave()"""
        ...

    def JobRenderOutputCount(self):
        """integer count = JobRenderOutputCount()"""
        ...

    def JobRenderOutputName(self, index):
        """string name = JobRenderOutputName(integer index)"""
        ...

    def JobRenderOutputType(self, index):
        """integer type = JobRenderOutputType(integer index)"""
        ...

    def JobSetCurrent(self, job: object.Unknown):
        """ The client provides information about how to render a scene with a render job.
        This is a COM object with an ILxRenderJob interface, as described below.
        Frames, animations, turntables and baking can be rendered by providing a job
        to the render service.

        A specific render job can be set as the current job with this method, or the
        current job can be set to nothing by passing NULL.  Attempting to set the
        render job will fail if another job is currently being rendered.  The job
        provided will be AddRef()'ed by the service.

        JobSetCurrent(object job)"""
        ...

    def JobStart(self):
        """ This method can be used to start rendering the current job, using the
        properties of the job to render the scene.  This function does not block,
        and will return immediately.  Status updates are sent to various methods
        on the job object itself.

        JobStart()"""
        ...

    def JobStats(self):
        """ This returns an ILxRenderStats container object containing information about the current
        render  See the ILxRenderStats description below for more information.  The container and
        the individual stats objects are dynamically updated while rendering, so you can hold on
        to the container object for the life of the render.  The object must be released when no
        longer needed.

        object = JobStats()"""
        ...

    def JobStatus(self):
        """ This returns the current status of a render job as an LxResult code.

        - LXe_RENDER_IDLE
        A job is loaded (JobCurrent() would succeed), but is not currently rendering
        a frame.  The system is effectively idle and waiting for JobStart() to be
        called, or for a new job to be loaded.
        
        - LXe_RENDER_RENDERING
        Returns true if the currently loaded job is rendering a frame.
        
        - LXe_RENDER_NO_JOB
        There is no current current job (and thus JobCurrent() would fail).  A new
        job must be set with JobSetCurrent() before calling JobStart().
        
        - LXe_RENDER_ABORTING
        JobAbort() was called and the job is in the process of aborting, but has not
        yet finished.

        JobStatus()"""
        ...

    def RefreshProgressImageMetrics(self):
        """RefreshProgressImageMetrics()"""
        ...

    def RenderEffectFromRenderType(self, type):
        """string effectName = RenderEffectFromRenderType(integer type)"""
        ...

    def RenderEffectToType(self, effect):
        """(integer type,integer size) = RenderEffectToType(string effect)"""
        ...

    def ScriptQuery(self):
        """Unknown object = ScriptQuery()"""
        ...

    def UpdateProgressImage(self):
        """UpdateProgressImage()"""
        ...



class RenderCache(object):
    def CreateRenderCache(self, createFlags):
        """RenderCache object = CreateRenderCache(integer createFlags)"""
        ...



class Scene(object):
    def AllocEmptyCollection(self):
        """ItemCollection object = AllocEmptyCollection()"""
        ...

    def ChannelVectorSize(self, mode):
        """integer size = ChannelVectorSize(integer mode)"""
        ...

    def ChannelVectorTextHints(self):
        """hints hints = ChannelVectorTextHints()"""
        ...

    def CloseCollection(self, collection, mode):
        """CloseCollection(object collection,integer mode)"""
        ...

    def CreateScene(self):
        """Scene object = CreateScene()"""
        ...

    def DestroyScene(self, scene):
        """DestroyScene(object scene)"""
        ...

    def GetMeshInstSourceItem(self, inst):
        """Item object = GetMeshInstSourceItem(object inst)"""
        ...

    def GetReplicatorEnumerator(self, replicatorItem):
        """ReplicatorEnumerator object = GetReplicatorEnumerator(object replicatorItem)"""
        ...

    def ItemGraphCollection(self, collection, type, graph, fwd):
        """ItemGraphCollection(object collection,integer type,string graph,integer fwd)"""
        ...

    def ItemSubTypeByIndex(self, type, index):
        """string subtype = ItemSubTypeByIndex(integer type,integer index)"""
        ...

    def ItemSubTypeCount(self, type):
        """integer count = ItemSubTypeCount(integer type)"""
        ...

    def ItemTypeByIndex(self, index):
        """integer type = ItemTypeByIndex(integer index)"""
        ...

    def ItemTypeCommonChannels(self, item1, item2):
        """integer count = ItemTypeCommonChannels(object item1,object item2)"""
        ...

    def ItemTypeCount(self):
        """integer = ItemTypeCount()"""
        ...

    def ItemTypeGetTag(self, type, tag, super):
        """string value = ItemTypeGetTag(integer type,string tag,integer super)"""
        ...

    def ItemTypeLookup(self, name: str) -> int:
        """ Given a type name, this returns the type ID.

        integer type = ItemTypeLookup(string name)"""
        ...

    def ItemTypeName(self, type):
        """string name = ItemTypeName(integer type)"""
        ...

    def ItemTypeSuper(self, type):
        """integer super = ItemTypeSuper(integer type)"""
        ...

    def ItemTypeSupportsInterface(self, type, guid):
        """boolean = ItemTypeSupportsInterface(integer type,string guid)"""
        ...

    def ItemTypeTest(self, what, isA):
        """boolean = ItemTypeTest(integer what,integer isA)"""
        ...

    def LoadImage(self, scene, path, monitor):
        """Item object = LoadImage(object scene,string path,object monitor)"""
        ...

    def MeshInstanceByIndex(self, mesh, index):
        """Item object = MeshInstanceByIndex(object mesh,integer index)"""
        ...

    def MeshInstanceCount(self, mesh):
        """integer = MeshInstanceCount(object mesh)"""
        ...

    def Root(self):
        """Scene object = Root()"""
        ...

    def ScriptQuery(self):
        """Unknown object = ScriptQuery()"""
        ...

    def SubSceneAdd(self, scene, other, refItems):
        """SubSceneAdd(object scene,object other,integer refItems)"""
        ...

    def SubSceneLoad(self, scene, path, monitor):
        """Scene object = SubSceneLoad(object scene,string path,object monitor)"""
        ...



class ScriptSys(object):
    def ByIndex(self, index):
        """ScriptManager object = ByIndex(integer index)"""
        ...

    def Count(self):
        """integer count = Count()"""
        ...

    def Desc(self, manager):
        """string name = Desc(object manager)"""
        ...

    def KitByIndex(self, index, visible):
        """Kit object = KitByIndex(integer index,integer visible)"""
        ...

    def KitCount(self, visible):
        """integer count = KitCount(integer visible)"""
        ...

    def KitLookup(self, name):
        """Kit object = KitLookup(string name)"""
        ...

    def Lookup(self, name):
        """ScriptManager object = Lookup(string name)"""
        ...

    def NameByIndex(self, index):
        """string name = NameByIndex(integer index)"""
        ...

    def ResolveAlias(self, alias):
        """string path = ResolveAlias(string alias)"""
        ...

    def ScriptQuery(self):
        """Unknown object = ScriptQuery()"""
        ...

    def UserName(self, manager):
        """string name = UserName(object manager)"""
        ...

    def UserValueByIndex(self, index):
        """UserValue object = UserValueByIndex(integer index)"""
        ...

    def UserValueCount(self):
        """integer count = UserValueCount()"""
        ...

    def UserValueLookup(self, name):
        """UserValue object = UserValueLookup(string name)"""
        ...



class Selection(object):
    def AbortBatch(self):
        """AbortBatch()"""
        ...

    def Allocate(self, name: str) -> object:
        """SelectionType object = Allocate(string name)"""
        ...

    def ByIndex(self, type, idx) -> int:
        """pointer = ByIndex(integer type,integer idx)"""
        ...

    def Clear(self, type: int):
        """ This is like Drop() but doesn't change the current selection mode.

        Clear(integer type)

        """
        ...

    def Count(self, type: int) -> int:
        """integer = Count(integer type)"""
        ...

    def CurrentSubTypes(self, type: int, sub: lx.object.storage, len: int):
        """integer num = CurrentSubTypes(integer type,unsigned[] sub,integer len)"""
        ...

    def CurrentType(self, types: lx.object.storage):
        """ This returns the most recent selection type -- the one the user acted on last.
        If 'types' is non-null, it will be an array of types terminated with zero,
        and the type returned will be one of the ones in the list.

        >>> selection_service = lx.service.Selection()
        >>> current_type = selection_service.CurrentType(lx.object.storage('i'))

        integer = CurrentType(unsigned[] types)

        """
        ...

    def Deselect(self, type, packet):
        """Deselect(integer type,pointer packet)"""
        ...

    def Drop(self, type):
        """Drop(integer type)"""
        ...

    def EndBatch(self):
        """EndBatch()"""
        ...

    def GetTime(self):
        """float = GetTime()"""
        ...

    def LookupName(self, type):
        """string = LookupName(integer type)"""
        ...

    def LookupType(self, name):
        """integer = LookupType(string name)"""
        ...

    def Recent(self, type):
        """pointer = Recent(integer type)"""
        ...

    def Remove(self, type, packet):
        """Remove(integer type,pointer packet)"""
        ...

    def ScriptQuery(self):
        """Unknown object = ScriptQuery()"""
        ...

    def Select(self, type, packet):
        """Select(integer type,pointer packet)"""
        ...

    def SetTime(self, time):
        """SetTime(float time)"""
        ...

    def StartBatch(self):
        """StartBatch()"""
        ...

    def State(self, type, packet):
        """ This is similar to Test(), but returns the actual selection state for
        the element. State can have one or more of the LXf_SELECTION_* bits
        set, or be LXf_SELECTION_NONE.

        integer = State(integer type,pointer packet)"""
        ...

    def Test(self, type, packet):
        """boolean = Test(integer type,pointer packet)"""
        ...

    def Toggle(self, type, packet):
        """Toggle(integer type,pointer packet)"""
        ...



class Shader(object):
    def CollectMaterials(self, collection):
        """CollectMaterials(object collection)"""
        ...

    def ColorBlendValue(self, c1, c2, opa, mode):
        """vector c = ColorBlendValue(vector c1,vector c2,float opa,integer mode)"""
        ...

    def ComputeFresnel(self, inRay, normalRay, normReflAmt):
        """float = ComputeFresnel(vector inRay,vector normalRay,float normReflAmt)"""
        ...

    def MeshShaderAccessor(self, meshItem):
        """Shader object = MeshShaderAccessor(object meshItem)"""
        ...

    def NextRandom(self, vector):
        """float = NextRandom(object vector)"""
        ...

    def PoissonOffset(self, vector):
        """(float u,float v) = PoissonOffset(object vector)"""
        ...

    def PolyShaderAccessor(self, meshItem, polyID):
        """Shader object = PolyShaderAccessor(object meshItem,id polyID)"""
        ...

    def RussianRoulette(self, vector, importance):
        """float = RussianRoulette(object vector,float importance)"""
        ...

    def SampleCloud(self, sample):
        """SampleCloud object = SampleCloud(object sample)"""
        ...

    def ScalarBlendValue(self, v1, v2, opa, mode):
        """float = ScalarBlendValue(float v1,float v2,float opa,integer mode)"""
        ...

    def SquareToCircle(self, x, y):
        """SquareToCircle(float[] x,float[] y)"""
        ...



class StdDialog(object):
    def AsyncMonitorAllocate(self, system, title):
        """AsyncMonitor object = AsyncMonitorAllocate(string system,string title)"""
        ...

    def AsyncMonitorAllocateWithoutAbort(self, system, title):
        """Unknown object = AsyncMonitorAllocateWithoutAbort(string system,string title)"""
        ...

    def AsyncMonitorLookup(self, ident):
        """Monitor object = AsyncMonitorLookup(string ident)"""
        ...

    def AsyncMonitorRelease(self, monitor):
        """AsyncMonitorRelease(object monitor)"""
        ...

    def AsyncMonitorSubAllocate(self, parent, title):
        """AsyncMonitor object = AsyncMonitorSubAllocate(object parent,string title)"""
        ...

    def AsyncMonitorSystemByIndex(self, index):
        """AsyncMonitorSystem object = AsyncMonitorSystemByIndex(integer index)"""
        ...

    def AsyncMonitorSystemCount(self):
        """integer count = AsyncMonitorSystemCount()"""
        ...

    def AsyncMonitorSystemLookup(self, name):
        """AsyncMonitorSystem object = AsyncMonitorSystemLookup(string name)"""
        ...

    def FileDialog(self, dlgObj):
        """FileDialog(object dlgObj)"""
        ...

    def MessageAllocate(self):
        """Message object = MessageAllocate()"""
        ...

    def MessageOpen(self, message, title, helpURL, cookie):
        """MessageOpen(object message,string title,string helpURL,string cookie)"""
        ...

    def MonitorAllocate(self, title: str) -> object.Monitor:
        """Monitor object = MonitorAllocate(string title)"""
        ...

    def MonitorRelease(self):
        """MonitorRelease()"""
        ...

    def MonitorReleaseObj(self, monitor: object.Unknown) -> None:
        """MonitorReleaseObj(object monitor)"""
        ...

    def ScriptQuery(self):
        """Unknown object = ScriptQuery()"""
        ...



class Tableau(object):
    def AllocVertex(self):
        """TableauVertex object = AllocVertex()"""
        ...

    def ScriptQuery(self):
        """Unknown object = ScriptQuery()"""
        ...

    def VertexFromFeatures(self, surfObj, vertex):
        """VertexFromFeatures(object surfObj,object vertex)"""
        ...



class TextEncoding(object):
    def Allocate(self):
        """TextEncoding object = Allocate()"""
        ...



class Thread(object):
    def CreateMutex(self) -> object.ThreadMutex:
        """ThreadMutex object = CreateMutex()"""
        ...

    def CreateCS(self) -> object.ThreadMutex:
        """ Create "Critical Section"

        ThreadMutex object = CreateCS()
        """
        ...

    def CreateGroup(self) -> object.ThreadGroup:
        """ Thread service interface allow new groups to be created.

        ThreadGroup object = CreateGroup()

        """
        ...

    def NumProcs(self) -> int:
        """ Determine how many processes are available

        integer = NumProcs()"""

        ...

    def IsMainThread(self) -> bool:
        """ Check if this is the main thread.

        bool = IsMainThread()

        """
        ...

    def CreateSlot(self, size: int, client: object.ThreadSlotClient) -> object.ThreadSlot:
        """ Allocating a new thread slot

        ThreadSlot object = CreateSlot(integer size,object client)

        """
        ...

    def ProcessShared(self, shared):
        """ You start with a single one of these objects that contains all the work. You then
        call the ProcesShared() method in the service. This will spawn enough of the shared
        work objects to populate the available computing resources. Each one will then process
        all the work it has, getting more from the main shared work object when they are
        empty. When all the work is done the sub-objects are destroyed.

        ProcessShared(object shared)"""
        ...

    def ProcessRange(self, data, startIndex: int, endIndex: int, rangeWorker: object.ThreadRangeWorker):
        """ Multi-processing over a range of indices (such as scanlines in an image).

        ProcessRange(pointer data,integer startIndex,integer endIndex,object rangeWorker)

        """
        ...

    def InitThread(self):
        """ If a plugin creates its own threads, using some external library (like pthreads or OpenMP),
        it needs to initialize itself before it can call Nexus functions. This function allows that.
        If the thread has already initialized itself, this function will do nothing.

        InitThread()

        """
        ...

    def CleanupThread(self):
        """ Once the thread has finished executing Nexus code, it needs to free the Nexus specific thread-data,
        so it must call CleanupThread, or there will be a memory leak.

        CleanupThread()

        """
        ...

    def ProcessWaterfall(self, waterfall: object.Waterfall, threads: int):
        """ This method takes a waterfall object and processes all the work it contains.
        New instances will be spawned to fill out the given number of threads, or
        one for each processor is the thread count is zero.

        ProcessWaterfall(object waterfall,integer threads)

        """
        ...


class Undo(object):
    def Apply(self, undo):
        """Apply(object undo)"""
        ...

    def Record(self, undo):
        """Record(object undo)"""
        ...

    def ScriptQuery(self):
        """Unknown object = ScriptQuery()"""
        ...

    def State(self):
        """integer = State()"""
        ...


class Value(object):
    def ScriptQuery(self) -> lx.object.Unknown:
        """ Gets the ILxScriptQueryID interface for the system.

        Unknown object = ScriptQuery()

        """
        ...

    def TextHintEncode(self, value: int, hint: lx.object.UIHints) -> str:
        """ This encodes a numeric value as a string.  If the 'buf' pointer is null, then
        a rolling buffer will be allocated and returned.  If the hint pointer is null
        then the value is written as a plain signed integer.

        This will return LXe_OK_INEXACT_MATCH when an integer is provided that does
        not exactly map to one of the choices.  This is only returned if there are
        choices.  LXe_OK_NO_CHOICES is returned if there are no choices at all.
        In both cases, the raw integer is encoded into the string buffer.  Both
        codes are "OK" codes, and do not signify an error, but rather provide hints
        about the content of the encoded string, and may help instruct an code path
        if you do need an exact match or were expecting choices.

        string = TextHintEncode(integer value, hints hint)

        """
        ...

    def TextHintDecode(self, buf: str, hint: lx.object.UIHints) -> int:
        """ This method decodes a string using the hint array.  If the string is a
        number it will be returned directly after being clamped to min or max limits.
        If nothing is recognized then the function end-of-list will be returned.
        This will return LXe_NOTFOUND when the string does not exactly match any
        text hints and cannot be converted into an integer (i.e., it doesn't start
        with a number).  LXe_OK_NO_CHOICES is returned when the string was
        sucessfully converted from a number into an integer and may have been
        constrained to any min/max hints present, but the hints contain no actual
        choices.  This may occur in the case of a hints array that is used only for
        min/max or similar properties, and is not meant to have a list of choices.

        integer value = TextHintDecode(string buf, hints hint)

        """
        ...

    def CreateValue(self, type: str) -> lx.object.Value:
        """ This method creates a new value object of the given type.

        Value object = CreateValue(string type)

        """
        ...

    def ValueType(self, type: str) -> int:
        """ This gets the intrinsic type for a given value type, as one of the LXi_TYPE_* choices.

        integer valType = ValueType(string type)

        """
        ...

    def FloatType(self, val: float) -> int:
        """ Check a float for NaN or infinity. A zero return value is OK.

        integer = FloatType(float val)

        """
        ...

    def GetFPS(self) -> float:
        """ Returns the global Frames Per Second.

        float = GetFPS()

        """
        ...

    def TimeToFrame(self, time: float) -> float:
        """ Given a time and using the global Frames Per Second, returns an equivalent frame.

        float = TimeToFrame(float time)

        """
        ...

    def FrameToTime(self, frame: float) -> float:
        """ Given a frame and using the global Frames Per Second, returns an equivalent time.

        float = FrameToTime(float frame)

        """
        ...

    def TimeToFrameFPS(self, time: float, fps: float) -> float:
        """ Given a time and a Frames Per Second, returns an equivalent frame.

        float = TimeToFrameFPS(float time,float fps)

        """
        ...

    def FrameToTimeFPS(self, frame: float, fps: float):
        """ Given a frame and a Frames Per Second, returns an equivalent time.

        float = FrameToTimeFPS(float frame,float fps)

        """
        ...

    def ConvertValues(self, from_str: str, to_str: str) -> lx.object.Unknown:
        """ Given two different value type names, returns an ILxValueConversion 
        object that can be used to convert from one type to the other.

        ValueConversion object = ConvertValues(string from_str,string to_str)

        """
        ...


class ValueHUD(object):
    def ClearHUD(self, cookie):
        """ClearHUD(string cookie)"""
        ...

    def ScriptQuery(self):
        """Unknown object = ScriptQuery()"""
        ...

    def SetHUDCommands(self, cookie, command1, command2, command3, alphaSort):
        """SetHUDCommands(string cookie,string command1,string command2,string command3,integer alphaSort)"""
        ...



class Variation(object):
    def InvalidateItem(self, item):
        """InvalidateItem(object item)"""
        ...

    def ScriptQuery(self):
        """Unknown object = ScriptQuery()"""
        ...



class VertexFeature(object):
    def AllocVertex(self):
        """TableauVertex object = AllocVertex()"""
        ...

    def DataType(self, ident):
        """string typeName = DataType(string ident)"""
        ...

    def Dimension(self, ident):
        """integer dimension = Dimension(string ident)"""
        ...

    def Lookup(self, type, name):
        """string ident = Lookup(integer type,string name)"""
        ...

    def Name(self, ident):
        """string name = Name(string ident)"""
        ...

    def ScriptQuery(self):
        """Unknown object = ScriptQuery()"""
        ...

    def TestCategory(self, ident, category):
        """boolean = TestCategory(string ident,string category)"""
        ...

    def Type(self, ident):
        """integer type = Type(string ident)"""
        ...

    def VectorType(self, ident):
        """string vecType = VectorType(string ident)"""
        ...



class View3Dport(object):
    def AddVirtualModel(self, vmodel: object.Unknown) -> None:
        """AddVirtualModel(object vmodel)"""
        ...

    def AllocGLViewport(self) -> object.Unknown:
        """Unknown object = AllocGLViewport()"""
        ...

    def Count(self) -> int:
        """integer = Count()"""
        ...

    def Current(self) -> int:
        """integer = Current()"""
        ...

    def GLMaterial(self, bin: object.Unknown, item: object.Unknown, view: object.Unknown) -> object.Unknown:
        """Unknown object = GLMaterial(object bin,object item,object view)"""
        ...

    def ImageToGLImage(self, image: object.Unknown) -> object.Unknown:
        """Unknown object = ImageToGLImage(object image)"""
        ...

    def InvalidateOverrider(self, scene: object.Unknown, pkgName: str):
        """integer = InvalidateOverrider(object scene,string pkgName)"""
        ...

    def Mouse(self) -> tuple[int, int]:
        """(integer,integer x,integer y) = Mouse()"""
        ...

    def RemoveVirtualModel(self, vmodel: object.Unknown) -> None:
        """RemoveVirtualModel(object vmodel)"""
        ...

    def ScriptQuery(self) -> object.Unknown:
        """Unknown object = ScriptQuery()"""
        ...

    def SetHitUVMap(self, name: str):
        """SetHitUVMap(string name)"""
        ...

    def SurfaceToViewObject(self, type: int, item: object.Unknown) -> object.Unknown:
        """Unknown object = SurfaceToViewObject(integer type,object item)"""
        ...

    def TriGroupToViewObject(self, type: int, triGroup: object.Unknown) -> object.Unknown:
        """Unknown object = TriGroupToViewObject(integer type,object triGroup)"""
        ...

    def UpdateVirtualModel(self, vmodel: object.Unknown):
        """UpdateVirtualModel(object vmodel)"""
        ...

    def View(self, index: int) -> object.Unknown:
        """ Get the View3D object at index.

        >>> view_service = lx.service.View3Dport()
        >>> view_index = view_service.Current()
        >>> unknown = view_service.View(view_index)
        >>> view = lx.object.View3D(unknown)
        >>> view.test()
        True

        Unknown object = View(integer index)

        """
        ...

